"""b_002_add_image_url_to_agent_sessions

Revision ID: 80d8a2607024
Revises: a8479577e492
Create Date: 2026-04-14 19:50:54.337469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d8a2607024'
down_revision: Union[str, None] = 'a8479577e492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_sessions', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_sessions', 'image_url')
    # ### end Alembic commands ###
